server.port=8050

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=nahid
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=product_schema

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




# Eureka Client Configuration
#Eureka server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
## Enable service registration with Eureka
eureka.client.register-with-eureka=true
## Enable service registry fetching e.g. to fetch other services registered with Eureka
eureka.client.fetch-registry=true
## Use IP address instead of hostname for service registration
eureka.instance.prefer-ip-address=true
## Enable shutdown endpoint
management.endpoint.shutdown.enabled=true
## Expose all endpoints e.g. health, info, metrics, etc.
management.endpoints.web.exposure.include=*
## Enable environment information e.g. active profiles, system properties, etc.
management.info.env.enabled=true



#Kafka Config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

#Kafka Topic Config
spring.kafka.topic.audit-topic=audit-topic

# Redis Config
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:default}
spring.data.redis.password=${REDIS_PASSWORD:redis123}

#Logging
logging.level.com.ecommerce.product=INFO
logging.level.org.springframework.kafka=WARN
logging.level.org.hibernate.SQL=DEBUG
