-- Run this in database: ecommerce
-- Assumes role/user `nahid` already exists

BEGIN;

-- 1) Create schemas (idempotent)
CREATE SCHEMA IF NOT EXISTS user_schema;
CREATE SCHEMA IF NOT EXISTS product_schema;
CREATE SCHEMA IF NOT EXISTS order_schema;
CREATE SCHEMA IF NOT EXISTS payment_schema;
CREATE SCHEMA IF NOT EXISTS notification_schema;
CREATE SCHEMA IF NOT EXISTS audit_schema;

-- 2) Ensure ownership/permissions
ALTER SCHEMA user_schema OWNER TO nahid;
ALTER SCHEMA product_schema OWNER TO nahid;
ALTER SCHEMA order_schema OWNER TO nahid;
ALTER SCHEMA payment_schema OWNER TO nahid;
ALTER SCHEMA notification_schema OWNER TO nahid;
ALTER SCHEMA audit_schema OWNER TO nahid;

GRANT USAGE, CREATE ON SCHEMA user_schema TO nahid;
GRANT USAGE, CREATE ON SCHEMA product_schema TO nahid;
GRANT USAGE, CREATE ON SCHEMA order_schema TO nahid;
GRANT USAGE, CREATE ON SCHEMA payment_schema TO nahid;
GRANT USAGE, CREATE ON SCHEMA notification_schema TO nahid;
GRANT USAGE, CREATE ON SCHEMA audit_schema TO nahid;

-- 3) Default privileges (for future objects created by nahid)
ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA user_schema
  GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO nahid;
ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA user_schema
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nahid;

ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA product_schema
  GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO nahid;
ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA product_schema
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nahid;

ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA order_schema
  GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO nahid;
ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA order_schema
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nahid;

ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA payment_schema
  GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO nahid;
ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA payment_schema
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nahid;

ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA notification_schema
  GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO nahid;
ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA notification_schema
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nahid;

ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA audit_schema
  GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO nahid;
ALTER DEFAULT PRIVILEGES FOR ROLE nahid IN SCHEMA audit_schema
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nahid;

COMMIT;
